name: Assembly-Bot Actions

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: dotnet build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
  publish:
    name: ssh pull, build and run
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Test
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password : ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command: whoami
    - name: Pull
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        command: cd ~/Assembly-Bot && git pull
    - name: Build
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey : ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        command: cd ~/Assembly-Bot && dotnet build
    #- name: Run