name: remote ssh pull, build & run
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: pull, build and run
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/Assembly-Bot
          git pull
          dotnet build
